swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"


paths:
  /user:
    get:
      operationId: "user.get"
      tags:
        - "User"
      summary: "Operations of performed on the user"
      description: "Read"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                fname:
                  type: "string"
                lname:
                  type: "string"
                timestamp:
                  type: "string"
    post:
      operationId: "create.user"



  /transfer:
    get:
      operationId: "transfers.getAll"

    post:
      operationId: "transfer.create"
      summary: "Create a new transfer"
        - name: PLN
          type: string
          required: true

        - name: PLN_C
          type: string
          required: true

        - name: accountnumber
          type: string
          required: true

        - name: firstname
          type: string
          required: true

        - name: lastname
          type: string
          required: true

        - name: city
          type: string
          required: true

        - name: address
          type: string
          required: true

        - name: titletransfer
          type: string
          required: true

    put:
      operationId: "update.transfer"
      summary: "update status of a transfer"
      parameters:
        - name: id
          type: string

  /transfer/{id}:
    get:
      operationId: transfer.getById

